name: 'Docusaurus Auto Actions'
branding:
  icon: "cloud-lightning"
  color: "blue"
description: 'Automatically process documents of Docusaurus.'
author: 'sunny0826'
inputs: 
  gh-page:
    description: 'github page repo'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gh-page }}
